### ISSUE TITLE
Add support for safe contracts (specially for slippage protection feature)

### ISSUE THREAD

**Issue by julien-devatom** [morpho-org/morpho-blue-bundlers#342]
- slippage management is delegated at the bundler level, but it is essential for safe users to be protected against slippage. For this reason, I would suggest reconsidering the "only for EOA" specification for allowing a safe to use the bundlers.

From my analysis, everything seems to be ok:
- The token transfers are done before calling the bundlers, so no need to support classic erc20 allowance
- The manager approval can be done before calling the bundlers

This is just an informational consideration.

**Comment by Rubilmax** [comment]
What shall we do about this issue?

**Comment by MerlinEgalite** [comment]
I don't think we should tackle it given the time constraint. However we can think about if Safe can safely use bundlers. If not we can add this requirement to the v2

**Comment by julien-devatom** [comment]
> I don't think we should tackle it given the time constraint. However we can think about if Safe can safely use bundlers. If not we can add this requirement to the v2

Just want to mention that it is crucial to support Safe asap after the mainnet release.

**Comment by MerlinEgalite** [comment]
I don't see any either, I think it's safe
