### ISSUE TITLE
`BundlerAction` not exported from main package import

### ISSUE THREAD

**Issue by Complexlity** [morpho-org/morpho-blue-bundlers#454]
![image](https://github.com/user-attachments/assets/393fd434-059e-404f-af86-b8b9673e8d66)

The documentation states to import `BundlerAction` from the main entry, but the installed package does not seem to have that. 
The `BundlerAction` could be accessed from going to `/pkg`

![image](https://github.com/user-attachments/assets/8a6ecd39-77fa-477c-b83c-488749fecfe1)

Could be resolve by:
1. Either make the main entry `/pkg` using the `exports` field in package.json
```
  "exports": {
    ".": {
      "require": "./pkg/index.js",
      "import": "./pkg/index.js",
      "types": "./pkg/index.d.ts"
    }
  },
```
Or
Updating the docs to import this way: 
 `import { BundlerAction  } from "@morpho-org/morpho-blue-bundlers/pkg"` instead

**Comment by Rubilmax** [comment]
Thank you for reporting this! Will fix this asap tomorrow

**Comment by MathisGD** [comment]
Bundler sdks are moved to https://github.com/morpho-org/sdks
